# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

# dummy fix for 403 error?
permissions:
  contents: write

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish SimpleWebServer.csproj -c Release -o bin/Release
    - name: Create Release Archive
      run: |
        # Create a zip archive of the release files using PowerShell
        Compress-Archive -Path ./bin/Release -DestinationPath SimpleWebServer.zip
      working-directory: ${{ github.workspace }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: SimpleWebServer
        path: SimpleWebServer.zip
        if-no-files-found: error
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::SimpleWebServer_$(date +"%d_%m_%Y_%H-%M")"
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: SimpleWebServer.zip
        
